# Generated by Django 2.2.4 on 2019-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190825_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_employer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
